import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { Workspace } from "@silo/core";

export interface WorkspaceRoute {
  host: string;
  target: string;
  protocol: "http" | "https";
}

export interface GatewaySyncResult {
  caddyFilePath: string;
  traefikFilePath: string;
}

export interface GatewaySyncOptions {
  outputDir?: string;
}

export function workspaceRoute(workspace: Workspace): WorkspaceRoute {
  return {
    host: workspace.domain,
    target: `127.0.0.1:${workspace.appPort}`,
    protocol: "http",
  };
}

export function workspaceUrl(workspace: Workspace): string {
  return `http://${workspace.domain}`;
}

export function syncGatewayConfigs(workspaces: Workspace[], options?: GatewaySyncOptions): GatewaySyncResult {
  const outputDir = options?.outputDir ?? join(homedir(), ".silo", "gateway");
  mkdirSync(outputDir, { recursive: true });

  const caddyFilePath = join(outputDir, "Caddyfile");
  const traefikFilePath = join(outputDir, "traefik.dynamic.yml");

  writeFileSync(caddyFilePath, renderCaddyfile(workspaces), "utf8");
  writeFileSync(traefikFilePath, renderTraefikDynamic(workspaces), "utf8");

  return { caddyFilePath, traefikFilePath };
}

export function renderCaddyfile(workspaces: Workspace[]): string {
  const header = [
    "{",
    "  auto_https off",
    "}",
    "",
    "# generated by silo; do not edit manually",
    "",
  ];

  const routes = workspaces
    .map((workspace) => {
      const route = workspaceRoute(workspace);
      return `${route.host} {\n  reverse_proxy ${route.target}\n}`;
    })
    .join("\n\n");

  return `${header.join("\n")}${routes}\n`;
}

export function renderTraefikDynamic(workspaces: Workspace[]): string {
  const routers = workspaces
    .map((workspace) => {
      const name = sanitizeName(workspace.slug);
      return [
        `    ${name}:`,
        `      rule: "Host(\`${workspace.domain}\`)"`,
        "      service: " + name,
        "      entryPoints:",
        "        - web",
      ].join("\n");
    })
    .join("\n");

  const services = workspaces
    .map((workspace) => {
      const name = sanitizeName(workspace.slug);
      return [
        `    ${name}:`,
        "      loadBalancer:",
        "        servers:",
        `          - url: "http://127.0.0.1:${workspace.appPort}"`,
      ].join("\n");
    })
    .join("\n");

  return [
    "# generated by silo; do not edit manually",
    "http:",
    "  routers:",
    routers || "    {}",
    "  services:",
    services || "    {}",
    "",
  ].join("\n");
}

function sanitizeName(input: string): string {
  return input.replace(/[^a-zA-Z0-9-]/g, "-");
}
